from .test_forms import *
from .test_logic import *
from .test_logic_domain import *
from .test_models import *
from .test_views import *
from .test_views_clinico import *
from .test_views_paciente import *
from .test_views_base import *
from .test_views_administrativo import *
from .test_forms_registro import *
