"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--0o*o#_p!l-d&a@ovw#x4352@fe!4gh%o^=$d!%j8=wptkj0fe'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gestion_citas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


#Formatos de hora profesionales
USE_L10N = False 
TIME_FORMAT = 'H:i'
TIME_INPUT_FORMATS = ['%H:%M']

# CONFIGURACIÓN DE LOGIN
LOGIN_URL = '/'          # Si intentan entrar sin permiso, los manda al login
LOGIN_REDIRECT_URL = 'dashboard'  # Al entrar bien, los manda al distribuidor
LOGOUT_REDIRECT_URL = '/'         # Al salir, vuelven al login

LANGUAGE_CODE = 'es-es'
USE_L10N = True
TIME_FORMAT = 'H:i' # Esto forzará el formato 24h en todo el sitio

JAZZMIN_SETTINGS = {
    # Títulos y bienvenida
    "site_title": "Hospital TFG",
    "site_header": "Gestión Hospitalaria",
    "site_brand": "Panel Admin",
    "welcome_sign": "Bienvenido al Sistema de Gestión de Citas",
    "copyright": "TFG Mario Reyes",
    
    # Menú lateral
    "search_model": "auth.User", # Barra de búsqueda superior para encontrar usuarios rápido

    # Iconos para tus modelos (usa iconos de FontAwesome 5)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "gestion_citas.Medico": "fas fa-user-md",
        "gestion_citas.Paciente": "fas fa-user-injured",
        "gestion_citas.Cita": "fas fa-calendar-check",
        "gestion_citas.Administrativo": "fas fa-id-card",
        "gestion_citas.Centro": "fas fa-hospital",
        "gestion_citas.Especialidad": "fas fa-stethoscope",
    },
    
    # Orden del menú lateral
    "order_with_respect_to": ["gestion_citas", "auth"],

    # Opciones de interfaz
    "show_ui_builder": True, # <--- ¡ESTO ES MÁGICO! (Te explico abajo)
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",   # Opciones: darkly, simplex, spacelab...
    # "dark_mode_theme": "darkly", # Si quieres modo oscuro
}