"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--0o*o#_p!l-d&a@ovw#x4352@fe!4gh%o^=$d!%j8=wptkj0fe'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        'DJANGO_ALLOWED_HOSTS',
        'tfg-citas-791788503447.europe-west1.run.app,localhost,127.0.0.1,192.168.1.2'
    ).split(',')
    if host.strip()
]

# Esta es la línea clave para quitar el error "Prohibido (403)"
CSRF_TRUSTED_ORIGINS = ['https://tfg-citas-791788503447.europe-west1.run.app']

# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gestion_citas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = []

# Internationalization
LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Formatos de hora profesionales
USE_L10N = True
TIME_FORMAT = 'H:i'
TIME_INPUT_FORMATS = ['%H:%M']

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# CONFIGURACIÓN DE LOGIN
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# ==========================================
# CONFIGURACIÓN DE JAZZMIN (TEMA VISUAL)
# ==========================================
JAZZMIN_SETTINGS = {
    "site_title": "Hospital TFG",
    "site_header": "Gestión Hospitalaria",
    "site_brand": "Panel Admin",
    "welcome_sign": "Bienvenido al Sistema de Gestión de Citas",
    "copyright": "TFG Mario Reyes",
    
    "search_model": "auth.User",

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "gestion_citas.Medico": "fas fa-user-md",
        "gestion_citas.Paciente": "fas fa-user-injured",
        "gestion_citas.Cita": "fas fa-calendar-check",
        "gestion_citas.Administrativo": "fas fa-id-card",
        "gestion_citas.Centro": "fas fa-hospital",
        "gestion_citas.Especialidad": "fas fa-stethoscope",
        "gestion_citas.GestionHorario": "fas fa-clock", 
    },
    
    "order_with_respect_to": ["gestion_citas", "auth"],
    
    # Lo apagamos un momento para que deje de tirar de la memoria de tu navegador
    "show_ui_builder": False, 
    
    # ---> ESTO FUERZA A QUE TU CREADOR DE HORARIOS NO TENGA PESTAÑAS <---
    "changeform_format_overrides": {
        "gestion_citas.gestionhorario": "single",
        "auth.user": "single",  # Desactiva pestañas para que salgan todos los campos de golpe
    },
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",   
}

# Clave primaria por defecto para modelos
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==========================================
# CONFIGURACIÓN DE CORREO ELECTRÓNICO (R7, R15)
# ==========================================
# Para desarrollo, imprimimos los emails en la consola para depurar fácilmente:
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# ACTIVANDO REDIRECCIÓN SMTP REAL PARA LA DEFENSA (Epic 3)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'tfgcitas@gmail.com'

# EVITAR FILTRACIONES EN GITHUB (Epic 3 - Seguridad)
# Cargamos la contraseña desde un archivo .env local (excluido en .gitignore)
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
SITE_BASE_URL = os.environ.get('SITE_BASE_URL', 'http://127.0.0.1:8000')

# Mini-helper para leer .env sin dependencias externas si existe
dotenv_path = os.path.join(BASE_DIR, '.env')
if os.path.exists(dotenv_path):
    with open(dotenv_path) as f:
        for line in f:
            line_strip = line.strip()
            if line_strip.startswith('EMAIL_HOST_PASSWORD='):
                EMAIL_HOST_PASSWORD = line_strip.split('=', 1)[1]
            elif line_strip.startswith('SITE_BASE_URL='):
                SITE_BASE_URL = line_strip.split('=', 1)[1]


DEFAULT_FROM_EMAIL = 'tfgcitas@gmail.com'



# NOTA: Cuando pases a producción (ej. con Gmail), comenta la línea anterior y usa esto:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'tu_correo@gmail.com'
# EMAIL_HOST_PASSWORD = 'tu_contraseña_de_aplicacion'

# ==========================================
# CONFIGURACIÓN DE ARCHIVOS ESTÁTICOS (PRODUCCIÓN)
# ==========================================
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')