# Generated by Django 6.0.1 on 2026-01-22 10:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0002_medicoprofile_pacienteprofile_delete_medico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicoProfile',
            new_name='Medico',
        ),
        migrations.RenameModel(
            old_name='PacienteProfile',
            new_name='Paciente',
        ),
    ]
