# Generated by Django 6.0.1 on 2026-03-04 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0006_alter_cita_urgencia_propuestareasignacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionHorario',
            fields=[
            ],
            options={
                'verbose_name': 'Gestión de Horario',
                'verbose_name_plural': 'Gestión de Horarios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion_citas.medico',),
        ),
    ]
