# Generated by Django 6.0.1 on 2026-03-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0008_configuracionreasignacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('C', 'Confirmada'), ('X', 'Cancelada'), ('R', 'En espera de reasignación')], default='C', max_length=1),
        ),
    ]
