# Generated by Django 5.1.1 on 2026-03-18 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0009_alter_administrativo_id_alter_centro_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionreasignacion',
            options={'verbose_name': 'Configuración de Reasignación', 'verbose_name_plural': 'Configuración de Reasignaciones'},
        ),
        migrations.AlterField(
            model_name='propuestareasignacion',
            name='hueco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='es_propuesta_de', to='gestion_citas.cita'),
        ),
    ]
