# Generated by Django 5.1.1 on 2026-03-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0010_alter_configuracionreasignacion_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='propuestareasignacion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'PENDIENTE')), fields=('hueco',), name='unique_pending_propuesta_per_hueco'),
        ),
    ]
