# Generated by Django 5.1.7 on 2026-04-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0012_consultamedica_receta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultamedica',
            name='diagnostico',
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='antecedentes_alergias',
            field=models.TextField(blank=True, help_text='RAM, antecedentes familiares...', null=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='enfermedad_actual',
            field=models.TextField(blank=True, help_text='Descripción narrativa del episodio...', null=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='exploracion_fisica',
            field=models.TextField(blank=True, help_text='Constantes y exploración por aparatos...', null=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='juicio_clinico',
            field=models.TextField(blank=True, help_text='Diagnóstico final o presuntivo', null=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='plan_recomendaciones',
            field=models.TextField(blank=True, help_text='Medidas generales, derivaciones...', null=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='pruebas_complementarias',
            field=models.TextField(blank=True, help_text='Rx, Analíticas...', null=True),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Notas de control interno', null=True),
        ),
    ]
