# Generated by Django 5.1.7 on 2026-04-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0013_remove_consultamedica_diagnostico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultamedica',
            old_name='enfermedad_actual',
            new_name='descripcion_problema',
        ),
        migrations.RenameField(
            model_name='consultamedica',
            old_name='juicio_clinico',
            new_name='diagnostico_principal',
        ),
        migrations.RenameField(
            model_name='consultamedica',
            old_name='exploracion_fisica',
            new_name='exploracion_medica',
        ),
        migrations.RenameField(
            model_name='consultamedica',
            old_name='pruebas_complementarias',
            new_name='pruebas_solicitadas',
        ),
        migrations.RemoveField(
            model_name='consultamedica',
            name='plan_recomendaciones',
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='tratamiento_pautas',
            field=models.TextField(blank=True, help_text='Medidas generales, derivaciones, reposo...', null=True),
        ),
    ]
