# Generated by Django 5.1.7 on 2026-04-05 11:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0014_rename_enfermedad_actual_consultamedica_descripcion_problema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='token_verificacion',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
