# Generated by Django 5.1.7 on 2026-04-05 11:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0016_alter_consultamedica_token_verificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultamedica',
            name='token_verificacion',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
