# Generated by Django 5.1.7 on 2026-04-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0017_alter_consultamedica_token_verificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='dni',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
