# Generated by Django 5.1.7 on 2026-04-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0018_paciente_dni_paciente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='nivel_cascada',
            field=models.IntegerField(default=0, help_text='Control de profundidad de la reacción en cadena (máx 5)'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('C', 'Confirmada'), ('X', 'Cancelada'), ('R', 'En espera de reasignación'), ('A', 'Atendida')], default='C', max_length=1),
        ),
    ]
