# Generated by Django 5.2.11 on 2026-05-09 10:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0019_cita_nivel_cascada_alter_cita_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionreasignacion',
            options={'verbose_name': 'Configuración de Reasignación', 'verbose_name_plural': 'Configuraciones de Reasignación'},
        ),
        migrations.AddField(
            model_name='propuestareasignacion',
            name='token_respuesta',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='Token único para la validación de la arquitectura One-Click.', null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='nivel_cascada',
            field=models.IntegerField(default=0, help_text='Control de profundidad de la reasignación automática.'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='urgencia',
            field=models.IntegerField(choices=[(3, 'Alta'), (2, 'Media'), (1, 'Baja')], default=1),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='antecedentes_alergias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='descripcion_problema',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='diagnostico_principal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='exploracion_medica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='pruebas_solicitadas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultamedica',
            name='tratamiento_pautas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propuestareasignacion',
            name='fecha_limite',
            field=models.DateTimeField(help_text='Fecha límite para la validez de la oferta.'),
        ),
    ]
