# Generated by Django 5.2.11 on 2026-05-09 10:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0020_alter_configuracionreasignacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuestareasignacion',
            name='token_respuesta',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único para la validación de la arquitectura One-Click.', unique=True),
        ),
    ]
