# Generated by Django 5.2.11 on 2026-05-09 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0021_alter_propuestareasignacion_token_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='gestion_citas.paciente'),
        ),
    ]
