# Generated by Django 5.1.7 on 2026-05-12 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0022_alter_cita_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuestareasignacion',
            name='hueco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='es_propuesta_de', to='gestion_citas.cita'),
        ),
    ]
